@startuml
'https://plantuml.com/class-diagram

Server "1"*--"1" AcceptThread
AcceptThread "1"*--"1" Menu


Menu "1"*--"1" GameHandler
GameHandler *-- "0..*" RunGames

GameHandler "1" *-- "1" GamesNoStartedMonitor
GamesNoStartedMonitor "1" *-- "0..*" GamesNoStarted


Menu"1"*--"1"ClientsMonitor
ClientsMonitor"1"*--"1"ClientsHandler
ClientsHandler"1"*--"0..*"ClientHandler
ClientHandler "1"*--"1"ClientThread
ClientThread "1"*--"1" ComandHandler
ClientThread "1"*--"1" ServerMenuProtocol
ServerMenuProtocol "1"*--"1"  Socket

RunGames "1"*--"0..*" GameThread

ProtocolSend "1"*--"1" SnapEventQueue
GameThread "1" *-- "0..*" ActionEventQueue
ActionEventQueue "1" *-- "0..*" RunGame
RunGame "1" *-- "1" SnapHandler
RunGame "1" *-- "0..*" Car
RunGame "1" *-- "0..*" Ball

GameThread "1" *-- "2..*" GamingClients
GamingClients "1"*--"1" ProtocolSend
GamingClients "1"*--"1" ProtocolRecv
ProtocolRecv "1"--"1" GamingComandHandler
GamingComandHandler "1"--"1" GamingComand
GamingComand <|-- GamingComandJump
GamingComand <|-- GamingComandTurbo
GamingComand <|-- GamingComandRight
GamingComand <|-- GamingComandLeft


ComandHandler "1"--"1" Comand
Comand <|-- ComandWithParameters
Comand <|-- ComandList
ComandWithParameters <|-- ComandAdd
ComandWithParameters <|-- ComandQuit
ComandWithParameters <|-- ComandCreate




@enduml